# Generated by Django 4.1.3 on 2022-12-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=100)),
                ('name', models.CharField(default='', max_length=100)),
                ('pokemons', models.JSONField(null=True)),
            ],
        ),
    ]
