# Generated by Django 4.1.3 on 2022-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('areas', models.JSONField(null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('region', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.JSONField(null=True)),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
