# Generated by Django 4.1.3 on 2022-12-01 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='location',
            new_name='locations',
        ),
    ]
