# Generated by Django 4.1.3 on 2022-12-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pokemonstorage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonstorage',
            name='is_party_member',
        ),
    ]
