# Generated by Django 4.1.3 on 2022-12-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_pokemonstorage_is_party_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonstorage',
            name='is_party_member',
            field=models.BooleanField(default=False),
        ),
    ]
