# Generated by Django 4.1.3 on 2022-12-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_region_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='locations',
            field=models.JSONField(null=True),
        ),
    ]
