# Generated by Django 4.1.3 on 2022-12-02 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_region_locations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='locations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locations', to='api.location'),
        ),
    ]
